name: Auto Assign Project

on: [pull_request, issues]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Run assignment to one project
      uses: docker://srggrs/assign-one-project-github-action:1.1.0
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/askap-vast/askap-pipeline/projects/1'
