name: Auto Assign Issues & PRs to Project

on: [pull_request, issues]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Run issues assignment to one project
      uses: alex-page/github-project-automation-plus@v0.1.0
      if: github.event_name == 'issues' && github.event.action == 'opened'
      with:
        project: Pipeline initial release
        column: To do
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run PRs assignment to one project
      uses: alex-page/github-project-automation-plus@v0.1.0
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      with:
        project: Pipeline initial release
        column: In progress
        repo-token: ${{ secrets.GITHUB_TOKEN }}
